### ISSUE TITLE
Which version of Graphviz?

### ISSUE THREAD

**Issue by srfoster** [pykello/racket-graphviz#4]
When I run any of the examples, I get (on Linux):

```
Format: "json" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz vrml wbmp x11 xdot xdot1.2 xdot1.4 xlib
```

I guessing perhaps I'm using the wrong version.  What's the appropriate one?

**Comment by pykello** [comment]
@srfoster Which Linux distro and which version are you using?

It was added in 2.40.0. See https://gitlab.com/graphviz/graphviz/blob/master/ChangeLog#L38

**Comment by srfoster** [comment]
I was using Xenial, and the version was 2.38.  Thanks!  I hadn't realized how old the graphviz package was.
